// <auto-generated />
using System;
using GymTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GymTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("GymTracker.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Admin",
                            Category = "Running",
                            CategoryColor = "#0a6640",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The ASICS Los Angeles Marathon course takes you from Stadium to the Stars, showcasing the vibrant neighborhoods and famous landmarks of this dynamic city",
                            Icon = "fa-solid fa-person-running",
                            Link = "https://www.mccourtfoundation.org/event/los-angeles-marathon/?utm_source=raceraves&utm_medium=listing&utm_campaign=raceraves2025",
                            Location = "Los Angeles, CA",
                            Title = "Los Angeles Marathon"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Admin",
                            Category = "Running",
                            CategoryColor = "#148a50",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The race starts along the Pacific Coast Highway and passes by the famous Huntington Beach pier",
                            Icon = "fa-solid fa-person-running",
                            Link = "https://www.runsurfcity.com",
                            Location = "Hunington Beach, CA",
                            Title = "Surf City Marathon"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Admin",
                            Category = "Running",
                            CategoryColor = "#0c5f3b",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Get ready for this year's Jingle Bell Run, the original festive race for charity brought to you by the Arthritis Foundation",
                            Icon = "fa-solid fa-person-running",
                            Link = "https://events.arthritis.org/jbrocie",
                            Location = "Angel Stadium, Anaheim, CA",
                            Title = "Jingle Bell Run Orange County & Inland Empire"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Admin",
                            Category = "Expo",
                            CategoryColor = "#0c5f3b",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Join thousands of fitness fanatics—bodybuilders, powerlifters, jiu-jitsu athletes, functional fitness warriors, trainers, and weekend warriors alike—for a weekend of sweat, strength, and skill.",
                            Icon = "fa-solid fa-dumbbell",
                            Link = "https://www.thefitexpo.com/cities/anaheim/",
                            Location = "Anaheim, CA",
                            Title = "The FitExpo"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Admin",
                            Category = "Running/Expo",
                            CategoryColor = "#0c5f3b",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The OC Lifestyle and Fitness Expo will be a 2-day extravaganza at the OC Fair & Event Center Exhibit Hall.",
                            Icon = "fa-solid fa-dumbbell",
                            Link = "https://ocmarathon.com/lifestyle-fitness-expo/",
                            Location = "Costa Mesa, CA",
                            Title = "OC Marathon Running Event"
                        });
                });
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("GymTracker.Models.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<int?>("WorkoutEntryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutEntryId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("GymTracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateJoined")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("BLOB");

                    b.Property<string>("ProfileImageMimeType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pronouns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("WorkoutEntries");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("GymTracker.Models.Set", b =>
                {
                    b.HasOne("GymTracker.Models.WorkoutEntry", "WorkoutEntry")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutEntryId");

                    b.Navigation("WorkoutEntry");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutEntry", b =>
                {
                    b.HasOne("GymTracker.Models.WorkoutSession", "Session")
                        .WithMany("WorkoutEntries")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutSession", b =>
                {
                    b.HasOne("GymTracker.Models.User", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GymTracker.Models.User", b =>
                {
                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutEntry", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("GymTracker.Models.WorkoutSession", b =>
                {
                    b.Navigation("WorkoutEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
